### ISSUE TITLE
Not compiling if texlive-full not installed

### ISSUE THREAD

**Issue by torydebra** [AndrePatri/PhDBiorobReportTemplate#1]
But I solved installing only the luatex package, instead of the `texlive-full`:

```bash
sudo apt-get install texlive-luatex
```

**Comment by AndrePatri** [comment]
Addressed by commit [5b4b482](https://github.com/AndrePatri/PhDBiorobReportTemplate/commit/5b4b482c9e3abd3aa86d2cddc43b1bc98c085250). 
Thanks for the feedback @torydebra.
