### ISSUE TITLE
Easier biblio handling with \fullcite and biblatex magic

### ISSUE THREAD

**Issue by torydebra** [AndrePatri/PhDBiorobReportTemplate#4]
If you use biblatex, you can use `\fullcite `to print full citation instead of put it manually. With the dontbib category the entries added with `\fullcite` will not be considered by the `\printbibliography`

What it is necessary:
- in the main.tex:
	```tex
	\usepackage[backend=bibtex, style=ieee, maxbibnames=99]{biblatex}
	\addbibresource{refs/refs.bib}
	\DeclareBibliographyCategory{dontbib}
	\addtocategory{dontbib}{TPO, TPO2, TPO3}
	\preto\fullcite{\AtNextCite{\defcounter{maxnames}{99}}}
	```
  To be used instead of `\usepackage{cite}`, so comment it

- to print the biblio:
  ```tex
	%\bibliographystyle{unsrt}
	%\bibliography{refs/refs.bib}
	\printbibliography[notcategory=dontbib]
  ```

- for fullcitation
  ```tex
	\begin{enumerate}[label={[J.\arabic*]}]
		\item \fullcite{TPO}
		\item \fullcite{TPO2}
	\end{enumerate}  
  ```

Sorry, can't open a PR my tex is now full of my report

**Comment by AndrePatri** [comment]
I'll handle the integration right away. Thanks @torydebra.

**Comment by AndrePatri** [comment]
Solved by commit [1ce1888](https://github.com/AndrePatri/PhDBiorobReportTemplate/commit/1ce18889cfe4b423fbe85b261ae88a0a02d055b5). 
Some notes: 
- You can now generate a list of full citations using the command `\fullcitelist`, which takes two arguments: first, a label to be appended before the enumeration number and the key of you resource, as defined in you bibliography files. 
For example: `\fullcitelist{J}{dummy_journal1,dummy_journal2}` outputs 
![fullcitelist](https://github.com/AndrePatri/PhDBiorobReportTemplate/assets/90312267/7a46b071-0d79-4804-8b24-c5b5bd63c1a4) or `\fullcitelist{C}{dummy_conference1}` 
![fullcitelist2](https://github.com/AndrePatri/PhDBiorobReportTemplate/assets/90312267/e5e268ec-63d1-4479-9094-cf676d171aa3)

**Comment by torydebra** [comment]
So awesome

**Comment by torydebra** [comment]
just an addition, if you do not have texlive-full, `sudo apt install texlive-bibtex-extra` is necessary

**Comment by AndrePatri** [comment]
I'll add this in the documentation. 
Btw, it now possible to call the `\fullcitelist` command with an optional size to modify the indentation of the citation list. 
For example `\fullcitelist[0.5cm]{C}{dummy_conference1}` will add 0.5 to the default leftmargin of the enumeration
